<a href="https://colab.research.google.com/github/theochan/Machine-Learning/blob/master/DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()
dataset = pd.DataFrame(data['data'], columns=data['feature_names'])
dataset['target'] = data['target']
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
dtc = DecisionTreeClassifier()
dtc_scaled = DecisionTreeClassifier()

dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

dtc_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = dtc_scaled.predict(X_test_scaled)

In [ ]:
confusion_matrix(y_test, y_pred)

array([[44,  3],
       [ 9, 58]])

In [ ]:
confusion_matrix(y_test, y_pred_scaled)

array([[44,  3],
       [ 8, 59]])

In [ ]:
accuracy_score(y_test, y_pred)

0.8947368421052632

In [ ]:
accuracy_score(y_test, y_pred_scaled)

0.9035087719298246

Almost same as Naives Bayes. Try using entropy as criterion.

In [10]:
dtc = DecisionTreeClassifier(criterion='entropy')
dtc_scaled = DecisionTreeClassifier(criterion='entropy')

dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)

dtc_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = dtc_scaled.predict(X_test_scaled)

In [11]:
confusion_matrix(y_test, y_pred)

array([[44,  3],
       [ 5, 62]])

In [12]:
confusion_matrix(y_test, y_pred_scaled)

array([[43,  4],
       [ 7, 60]])

In [14]:
accuracy_score(y_test, y_pred)

0.9298245614035088

In [15]:
accuracy_score(y_test, y_pred_scaled)

0.9035087719298246